server:
  port: 8081

ethereum:
  netVersion: 37
  host: 127.0.0.1
  port: 8070
  mnemonic: 'in rock machine head the dark side of the moon third stage'
  from: '0xc5776c5d4ba76dd38424a160927c6b7054b55edd'
  gasPrice:
  gasLimit:
  
contracts:
  MetaCoin:
    address: '0x05Dc3f6E4b1beE0c1F7acBc29E61a8091e3F8DF6'
  ServiceProgramFactory:
    address: '0x05d3B2186a0f3DD5400020f7296E1E9A10d63BAf'

